### ISSUE TITLE
Current Weapons That Do Not Work

### ISSUE THREAD

**Issue by Mesagoppinmypants** [TheAnswer/Core3#5]
CBT weapons that do not work:
- Deathhammer Pistol
- Proton Carbine
- Heavy Carbonite Rifle
- Lava Cannon
- All of Melee

**Comment by dannuic** [comment]
If you think there's a bug in the code, please create a bug in our mantis at http://www.swgemu.com/bugs

GitHub isn't our primary development tool, and the guidelines on mantis will help you create a proper bug report with all the requisite information.

**Comment by Mesagoppinmypants** [comment]
LOL! My bad I thought this was my forked Core3 repo. lmao
