### ISSUE TITLE
Minor calculation issue

### ISSUE THREAD

**Issue by Tatwi** [TheAnswer/Core3#6]
Howdy, 

I was looking at  
https://github.com/TheAnswer/Core3/blob/unstable/MMOCoreORB/src/server/zone/objects/structure/events/StructureMaintenanceTask.cpp

recently and I noticed the following calculation that didn't quite look right, 

int threeMonthsOfMaintenance = 30 \* 24 \* structure->getMaintenanceRate();

That's 30 days \* 24 hours \* fee/hour. It's missing the \* 3 to get up to the three month mark, unless I am missing something, which is possible. :)

**Comment by TheAnswer** [comment]
the name of the var is wrong, the change from 3 to 1 month was intentional
